ALTER TABLE th_user_checkouts ALTER COLUMN table_id DROP NOT NULL;

ALTER TABLE th_user_checkouts
    ADD COLUMN IF NOT EXISTS order_type VARCHAR(20) DEFAULT 'DINE_IN',
    ADD COLUMN IF NOT EXISTS payment_method VARCHAR(20) DEFAULT 'WALLET',
    ADD COLUMN IF NOT EXISTS payment_status VARCHAR(20) DEFAULT 'PAID',
    ADD COLUMN IF NOT EXISTS cash_amount DECIMAL(10, 2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS cash_change DECIMAL(10, 2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS is_cashier BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS qr_string TEXT,
    ADD COLUMN IF NOT EXISTS qr_url TEXT;
